name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install
        run: |
          npm install
      - name: test-create-dist
        run: |
          npx prettier -c .
          npx eslint --ignore-pattern end-to-end-example .
          npm run dist
